### PR TITLE
Updated inquirer dependency to support Node 12 in Windows 10

### PR DESCRIPTION
**Pull request by iminguez**

### CODE REVIEW

**Comment by mcdado** [comment]
@jon-hall merge and publish a new version, please?

I'm using Windows Server 2019 and Node 12, and upgrading this dependency solved the issue reported by several people.

- https://github.com/jon-hall/pm2-windows-service/issues/51
- https://github.com/jon-hall/pm2-windows-service/issues/56

**Comment by adampenn** [comment]
any reason this isnt getting merged? seesm like its happening to a lot of people

**Comment by neversaid** [comment]
Well, agree with adampenn, this should be merged!

**Comment by Karrlllis** [comment]
Hi, please merge this PR! 

Ty

**Comment by Silventino** [comment]
@jon-hall would you mind merging this PR? It is essential.

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).

**Pull request closed without merging**
